ethereum:
  outputs:
    dev:
      dataset: ethereum_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: my-gcp-project
      threads: 4
      type: bigquery
  target: dev
